### ISSUE TITLE
本地引用会报错

### ISSUE THREAD

**Issue by Unfantasy** [sekaiamber/remote-console#15]
![wuti_y3 5 6rjn5 1sbriv](https://cloud.githubusercontent.com/assets/16619996/24438831/d7b6de0a-147c-11e7-81cd-ca748536597b.png)

**Comment by sekaiamber** [comment]
为了拥抱未来，这儿我们使用了相对协议，我们插入野狗脚本的时候，是类似这样的代码：

```html
<script type="text/javascript" src="//cdn.wilddog.com/sdk/js/2.4.4/wilddog-sync.js"></script>
```

请阅读README其中的Develop部分，使用Web服务来查看

**Comment by Unfantasy** [comment]
@sekaiamber 哦，原来这种是为了拥抱未来啊，我还以为这种的没有http://的好
